# Generated by Django 5.1.3 on 2025-06-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_nascimento',
            new_name='date_nasc',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='foto',
            new_name='photo',
        ),
    ]
