# Generated by Django 5.1.3 on 2025-06-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_data_nascimento_customuser_date_nasc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='events/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_init', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('regulation', models.FileField(blank=True, null=True, upload_to='events/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Occurrence',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
