# Generated by Django 5.1.3 on 2025-06-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_rename_events_occurrence_remove_badge_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='bolletin',
        ),
        migrations.AddField(
            model_name='attachments',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings_access',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement_user',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms_use',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volley_match',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntary',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bolletin',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
