# Generated by Django 5.1.3 on 2025-06-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_section_bolletin_attachments_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.IntegerField(default=99),
        ),
        migrations.CreateModel(
            name='Event_sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso')])),
                ('min_sport', models.IntegerField(default=1)),
                ('max_sport', models.IntegerField(default=99)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
