# Generated by Django 5.1.3 on 2025-06-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_age_event_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Coordenador de evento'), (2, 'Usuário comum'), (3, 'Marcador de pontos')], default=1),
            preserve_default=False,
        ),
    ]
