# Generated by Django 5.1.3 on 2025-06-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_event_user_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_sport',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='event_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='app.event'),
        ),
        migrations.AlterField(
            model_name='event_sport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_set', to='app.event'),
        ),
        migrations.AlterField(
            model_name='event_sport',
            name='max_sport',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='event_sport',
            name='min_sport',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
