# Generated by Django 5.1.3 on 2025-06-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team_sport_event_alter_customuser_event_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enrollment_init',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team_sport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sport_set', to='app.event'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntary_set', to='app.event'),
        ),
    ]
