# Generated by Django 5.1.3 on 2025-06-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_enrollment_end_event_enrollment_init_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='campus',
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
