# Generated by Django 5.1.3 on 2025-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_customuser_campus_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Coordenador de evento'), (2, 'Usuário comum'), (3, 'Marcador de pontos')], default=3),
        ),
    ]
