# Generated by Django 5.1.3 on 2025-06-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='team',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='campus',
        ),
    ]
