# Generated by Django 5.1.3 on 2025-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_player_campus_remove_team_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='hexcolor',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
