# Generated by Django 5.1.3 on 2025-06-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_team_hexcolor_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_sport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event_sport'),
        ),
    ]
