# Generated by Django 5.1.3 on 2025-07-26 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_team_sport_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='player_need_bulletin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_cpf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_date_nasc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_instagram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_rg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_sexo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='voluntary_need_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='voluntary_need_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='bulletin',
            field=models.FileField(blank=True, null=True, upload_to='bulletins/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cpf',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_nasc',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/person.png', null=True, upload_to='photo_player/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rg',
            field=models.FileField(blank=True, null=True, upload_to='rg/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Misto')], null=True),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/person.png', null=True, upload_to='photo_voluntary/'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='registration',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Event_need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_set', to='app.event')),
            ],
        ),
    ]
