# Generated by Django 5.1.3 on 2025-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_player_need_bulletin_event_player_need_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
