# Generated by Django 5.1.3 on 2025-07-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
