# Generated by Django 5.1.3 on 2025-08-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_sport',
            name='admin',
        ),
    ]
