# Generated by Django 5.1.3 on 2025-08-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_team_sport_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='match',
        ),
        migrations.AlterField(
            model_name='assistance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player_match'),
        ),
    ]
