# Generated by Django 5.1.3 on 2025-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_assistance_match_alter_assistance_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalties',
            name='type_penalties',
            field=models.IntegerField(choices=[(0, 'Cartão Vermelho'), (1, 'Cartão Amarelo'), (2, 'Falta'), (3, 'Nenhum')], default=3),
        ),
    ]
