# Generated by Django 5.1.3 on 2025-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo')], default=1),
        ),
    ]
