# Generated by Django 5.1.3 on 2025-08-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_attachments_public_alter_banner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='user',
        ),
    ]
