# Generated by Django 5.1.3 on 2025-09-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_attachments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='user_agent',
            new_name='browser',
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
    ]
