# Generated by Django 5.1.3 on 2025-09-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_user_agent_usersession_browser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='voluntary_need_photo',
            new_name='voluntary_need_address',
        ),
    ]
