# Generated by Django 5.1.3 on 2025-09-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_voluntary_need_photo_event_voluntary_need_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='player_need_bulletin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_cpf',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_date_nasc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_instagram',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_registration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_rg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='player_need_sexo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='voluntary_need_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='voluntary_need_registration',
        ),
    ]
