# Generated by Django 5.1.3 on 2025-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_event_player_need_bulletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='player_need_bulletin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_cpf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_date_nasc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_instagram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_rg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_sexo',
            field=models.BooleanField(default=True),
        ),
    ]
