# Generated by Django 5.1.3 on 2025-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_event_player_need_bulletin_event_player_need_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
