# Generated by Django 5.1.3 on 2025-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_player_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tutorial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
