# Generated by Django 5.1.3 on 2025-09-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_event_sport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_need',
            field=models.BooleanField(default=False),
        ),
    ]
