# Generated by Django 5.1.3 on 2025-09-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_event_team_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_need',
        ),
    ]
