# Generated by Django 5.1.3 on 2025-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_event_team_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_sport',
            name='fem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event_sport',
            name='masc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event_sport',
            name='mist',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso'), (10, 'Arremesso de disco')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso'), (10, 'Arremesso de disco')]),
        ),
    ]
