# Generated by Django 5.1.3 on 2025-10-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_event_sport_fem_event_sport_masc_event_sport_mist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='detailed',
            field=models.IntegerField(choices=[(0, 'Em instantes'), (1, 'Ao vivo'), (2, 'Pausada'), (3, 'Finalizada'), (4, 'Penaltis'), (5, 'Escalação A'), (6, 'Escalação B')], default=0),
        ),
        migrations.AlterField(
            model_name='event_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso'), (10, 'Arremesso de disco'), (11, 'Queimado')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Arremesso de peso'), (10, 'Arremesso de disco'), (11, 'Queimado')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em breve'), (1, 'Acontecendo'), (2, 'Finalizada')], default=0),
        ),
        migrations.AlterField(
            model_name='volley_match',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em breve'), (1, 'Acontecendo'), (2, 'Finalizada')], default=0),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntário'), (1, 'Técnico de modalidade esportiva'), (2, 'Apoio'), (3, 'Estagiário'), (4, 'Chefe de delegação'), (5, 'Organização')], default=0),
        ),
    ]
