# Generated by Django 5.1.3 on 2025-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_match_detailed_alter_event_sport_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_badge',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='detailed',
            field=models.IntegerField(choices=[(0, 'Em instantes'), (1, 'Ao vivo'), (2, 'Pausada'), (3, 'Finalizada'), (4, 'Penaltis'), (5, 'Escalação')], default=0),
        ),
        migrations.AlterField(
            model_name='player_match',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Nenhum'), (1, 'Reserva'), (2, 'Goleiro'), (3, 'Fixo'), (4, 'Ala 1'), (5, 'Ala 2'), (6, 'Pivô'), (7, 'Levantador'), (8, 'Oposto'), (9, 'Ponteiro 1'), (10, 'Ponteiro 2'), (11, 'Central'), (12, 'Líbero')], default=0),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='type_voluntary',
            field=models.IntegerField(choices=[(0, 'Voluntário'), (1, 'Técnico de modalidade esportiva'), (2, 'Apoio'), (3, 'Estagiário'), (4, 'Chefe de delegação'), (5, 'Organização'), (6, 'Árbitro')], default=0),
        ),
    ]
