# Generated by Django 5.1.3 on 2025-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_group_phase_match_location_match_group_phase_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Misto')], default=0),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.IntegerField(blank=True, choices=[(0, 'Fase de Grupos'), (1, 'Quartas de Final'), (2, 'Semifinal'), (3, 'Final')], default=0, null=True),
        ),
    ]
