# Generated by Django 5.1.3 on 2025-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_phase_sexo_alter_phase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='observations',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='team_match',
            name='technitian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team_sport',
            name='technitian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
