# Generated by Django 5.1.3 on 2025-10-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_sport',
            name='technitian',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_voluntary': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.voluntary'),
        ),
        migrations.CreateModel(
            name='Match_referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Árbitro principal'), (1, 'Assistente'), (2, 'Anotador'), (3, 'Cronometrista')], default=0, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='app.match')),
                ('referee', models.ForeignKey(blank=True, limit_choices_to={'type_voluntary': 6}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.voluntary')),
            ],
        ),
    ]
