# Generated by Django 5.1.3 on 2025-10-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_team_sport_technitian_match_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_referee',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Árbitro principal'), (1, 'Árbitro'), (2, 'Assistente'), (3, 'Anotador'), (4, 'Cronometrista')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='Authenticity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
