# Generated by Django 5.1.3 on 2025-10-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_match_referee_role_authenticity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_goal',
            field=models.ImageField(blank=True, default='defaults/person.png', null=True, upload_to='photo_player/'),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.TextField(blank=True, default='#02007a', max_length=7, null=True),
        ),
    ]
