# Generated by Django 5.1.3 on 2025-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_player_photo_goal_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='general_need_authorization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='general_need_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='general_need_unit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_photo_goal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team_need_color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team_need_description',
            field=models.BooleanField(default=True),
        ),
    ]
