# Generated by Django 5.1.3 on 2025-12-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_event_general_need_authorization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='classroom',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
