# Generated by Django 5.1.3 on 2025-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_classroom_player_unit_player_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntary',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
