# Generated by Django 5.1.3 on 2025-12-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_customuser_unit_team_unit_voluntary_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
        migrations.AlterField(
            model_name='player',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
    ]
