# Generated by Django 5.1.3 on 2025-12-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_event_unit_alter_customuser_unit_alter_player_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event_unit'),
        ),
    ]
