# Generated by Django 5.1.3 on 2025-12-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_customuser_unit_alter_team_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_unit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_set', to='app.event'),
        ),
    ]
