# Generated by Django 5.1.3 on 2026-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_event_unit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document_boss/'),
        ),
    ]
