# Generated by Django 5.1.3 on 2026-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_customuser_accepted_customuser_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='player_need_cep',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_city',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_need_course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
