# Generated by Django 5.1.3 on 2026-04-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_event_player_need_cep_event_player_need_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='player_need_city',
            new_name='player_need_municipality',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='city',
            new_name='municipality',
        ),
    ]
