# Generated by Django 5.1.3 on 2026-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_player_need_city_event_player_need_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='terms_declaration_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upload_intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
