# Generated by Django 5.1.3 on 2026-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_event_terms_declaration_text_event_terms_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_need_technician',
            field=models.BooleanField(default=True),
        ),
    ]
