# Generated by Django 5.1.3 on 2026-04-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_event_team_need_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_max',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
