# Generated by Django 5.1.3 on 2026-04-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='app.event'),
        ),
    ]
