# Generated by Django 5.1.3 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_accesslog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=1, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
