# Generated by Django 5.1.3 on 2026-04-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_event_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_badge',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='badge_set', to='app.event'),
            preserve_default=False,
        ),
    ]
