# Generated by Django 5.1.3 on 2026-04-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event_unit'),
        ),
    ]
