# Generated by Django 5.1.3 on 2026-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntary',
            name='registration',
            field=models.CharField(blank=True, default='00000000000', max_length=15, null=True),
        ),
    ]
