# Generated by Django 5.1.3 on 2026-05-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_voluntary_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tutorial',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
