# Generated by Django 5.1.3 on 2026-07-16 21:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_event_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_image', models.ImageField(upload_to='static\\images\\generators\x0cigurinha-jif-2.png')),
                ('width_mm', models.PositiveIntegerField(default=65)),
                ('height_mm', models.PositiveIntegerField(default=90)),
                ('photo_x', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('photo_y', models.FloatField(default=12.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('photo_width', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('photo_height', models.FloatField(default=55.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('photo_corner_radius', models.FloatField(default=8.0, help_text='Arredondamento das bordas da foto, em % da largura da área da foto.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('show_name', models.BooleanField(default=True)),
                ('name_y', models.FloatField(default=88.0, help_text='Posição vertical (%) do texto do nome, a partir do topo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('name_font_size', models.PositiveIntegerField(default=28)),
                ('name_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Template usado automaticamente quando nenhum outro for escolhido na geração.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Deixe em branco para um template global (disponível para todos os eventos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sticker_templates', to='app.event')),
            ],
            options={
                'verbose_name': 'Template de Figurinha',
                'verbose_name_plural': 'Templates de Figurinha',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
