# Generated by Django 5.1.3 on 2026-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_sticker_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker_template',
            name='base_image',
            field=models.ImageField(upload_to='static/images/generators/figurinha-jif-2.png'),
        ),
    ]
