# Generated by Django 5.1.3 on 2026-07-17 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_sticker_template_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badge_module_enabled',
            field=models.BooleanField(default=True, help_text='Habilita a geração de Crachás para este evento.'),
        ),
        migrations.AddField(
            model_name='event',
            name='sticker_module_enabled',
            field=models.BooleanField(default=True, help_text='Habilita a geração de Figurinhas para este evento.'),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='is_system_default',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='show_campus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='show_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='show_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='side_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='side_font_size',
            field=models.PositiveIntegerField(default=22, help_text='Tamanho da fonte do CAMPUS/ANO (textos verticais nas laterais).'),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='team_y',
            field=models.FloatField(default=93.0, help_text='Posição vertical (%) da linha do TIME, logo abaixo do nome.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sticker_template',
            name='base_image',
            field=models.ImageField(upload_to='sticker_templates/'),
        ),
    ]
