# Generated by Django 5.1.3 on 2026-07-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_event_badge_module_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker_template',
            name='is_system_default',
        ),
    ]
