# Generated by Django 5.1.3 on 2026-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_remove_sticker_template_is_system_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker_template',
            name='campus_side',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='left', help_text='Lado da figurinha onde o campus aparece.', max_length=5),
        ),
        migrations.AddField(
            model_name='sticker_template',
            name='year_side',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='right', help_text='Lado da figurinha onde o ano do evento aparece.', max_length=5),
        ),
    ]
