name: Feature Tests Actions
run-name: ${{ github.actor }} Test Code  🚀
on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]
  workflow_dispatch: # Permite execução manual
    inputs:
      approve_deploy:
        description: "Autorizar Deploy? (true/false)"
        required: true
        default: "false"

jobs:
  Testing-Deps:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.0, 3.11.5, 3.12.0]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Getting .env file
      run: |
        wget https://pastebin.com/raw/6Z7HS1x9 -O .env

    - name: Run Django Migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test

  Authorize-Deploy:
    needs: Testing-Deps
    runs-on: ubuntu-latest
    steps:
    - name: Check Test Results and Authorize Deploy
      id: authorize
      run: |
        if [ "${{ needs.Testing-Deps.result }}" == "success" ]; then
          echo "deploy=true" >> $GITHUB_ENV
        else
          echo "deploy=false" >> $GITHUB_ENV
          exit 1
        fi
    - name: Output Deploy Status
      run: |
        echo "Deploy authorized: ${{ env.deploy }}"
